/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as votingContractsNftSol from "./VotingContractsNFT.sol";
export type { votingContractsNftSol };
export type { MyVotingNFT } from "./MyVotingNFT";
