/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as votingContractsNftSol from "./VotingContractsNFT.sol";
export { MyVotingNFT__factory } from "./MyVotingNFT__factory";
